
import { PG_MERCHENT_ID, PG_SALT_KEY, PG_SALT_INDEX, PG_CALLBACK_URL, PG_CALL_MODE ,PG_API_URL ,PG_REDIRECT_URL } from "./env";

export const PG = {
    PG_MERCHENT_ID,
    PG_SALT_KEY,
    PG_SALT_INDEX,
    PG_CALLBACK_URL,
    PG_CALL_MODE,
    PG_API_URL,
    PG_REDIRECT_URL,
};

